on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [stable]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      run: make test
    - name: Upload code coverage
      if: matrix.platform == 'ubuntu-latest'
      uses: codecov/codecov-action@v3
      with:
        file: ./bin/cover.out
